services:
  web:
    build: .
    
    container_name: cinema_django_app
    
    ports:
      - "8000:8000"
      
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      
    restart: unless-stopped